/**
 * SolicitacaoPagamento
 * Solicitação de Pagamento
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SolicitacaoPagamento } from './solicitacaoPagamento';


export interface ALDETLFornecedores {
    numero?: number;
    tipo_de_prestador?: string;
    nome_da_marca?: string;
    alerta?: string;
    nome_fantasia?: string;
    grupo?: string;
    endereco?: string;
    complemento?: string;
    municipio?: string;
    uf?: string;
    cep?: string;
    telefone1?: string;
    telefone2?: string;
    email?: string;
    latitude?: string;
    longitude?: string;
    cnpj?: string;
    status?: string;
    razao_Social?: string;
    prazo_Pagamento?: string;
    agencia?: string;
    conta_Corrente?: string;
    codImportacaoALDLog?: number;
    solicitacao_Pagamento?: Array<SolicitacaoPagamento>;
}
