/**
 * SolicitacaoPagamento
 * Solicitação de Pagamento
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ALDETLCrepCode {
    cC_Crep_Code_Numero?: number;
    cC_Crep_Code_Descricao?: string;
    cC_Crep_Code_Nao_Exige_Valor_Total?: string;
    cC_Crep_Code_Garantia?: string;
    cC_Crep_Code_Exige_Valor_Peca?: string;
    cC_Crep_Code_Exige_Valor_Servico?: string;
    cC_Crep_Code_Exige_Valor_Total?: string;
    cC_Crep_Code_Rebil?: string;
    cC_Crep_Code_Exige_Quantidade?: string;
    cC_Crep_Code_Conta_Custo?: string;
    cC_Crep_Code_Conta_Receita?: string;
    cC_Crep_Code_Mensal?: string;
    cC_Crep_Code_Tipo_Rebil?: string;
    cC_Crep_Code_Exige_Imposto?: string;
    cC_Crep_Code_Conta_Investimento?: string;
    cC_Crep_Code_Veiculo_Reserva?: string;
    cC_Crep_Code_Auto_Rebil?: string;
    cC_Crep_Code_Exige_Km?: string;
    cC_Crep_Code_Tipo?: string;
    cC_Crep_Code_Tipo_Pneu?: string;
    cC_Crep_Code_Fabricante?: string;
    cC_Crep_Code_Livre?: string;
    cC_Crep_Code_Grupo_Descricao?: string;
    cC_Crep_Code_Data_Ultima_Atualizacao?: Date;
    cC_Crep_Code_Usuario_Ultima_Atualizacao?: string;
    data_Ultima_Atualizacao?: Date;
}
