/**
 * SolicitacaoPagamento
 * Solicitação de Pagamento
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface Exception {
    message?: string;
    data?: { [key: string]: any; };
    innerException?: Exception;
    stackTrace?: string;
    helpLink?: string;
    source?: string;
    hResult?: number;
}
