/**
 * SolicitacaoPagamento
 * Solicitação de Pagamento
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Exception } from './exception';


export interface Resposta {
    mensagem?: string;
    mensagemException?: string;
    status?: boolean;
    dados?: any;
    exception?: Exception;
}
