/**
 * SolicitacaoPagamento
 * Solicitação de Pagamento
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CategoriaNF } from './categoriaNF';
import { SolicitacaoPagamento } from './solicitacaoPagamento';


export interface SolicitacaoPagamentoDetalhe {
    id?: number;
    numero_nf: string;
    categoria_nf?: string;
    valor: number;
    dt_emissao: Date;
    dt_recebimento: Date;
    dt_vencimento: Date;
    crep_code?: number;
    qtd?: number;
    numero_contrato?: number;
    linha?: number;
    numero_po?: number;
    filial?: string;
    customer_rebill?: number;
    km?: number;
    chave_acesso?: string;
    obs?: string;
    placa?: string;
    placa_subst?: string;
    id_solicitacao_pagamento?: number;
    dt_criacao?: Date;
    dt_atualizacao?: Date;
    prd_id?: number;
    num_vistoria?: string;
    id_visual?: number;
    rebil_sn?: string;
    mes_fat?: string;
    fat_rebil_num?: number;
    dt_export_ged_fat?: Date;
    opcionais_veiculo?: number;
    acessorios_veiculo?: number;
    ipva?: number;
    dpvat?: number;
    licenciamento?: number;
    frete?: number;
    despachante?: number;
    outros_servicos?: number;
    reused_flag?: boolean;
    reused_flag_sn?: string;
    dfil?: string;
    tipo_export?: string;
    nao_rebill_ncva?: number;
    nao_rebill_cva_material?: number;
    nao_rebill_cva_servico?: number;
    solicitacao_Pagamento?: SolicitacaoPagamento;
    categoria_NF?: CategoriaNF;
}
