//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class ALD_ETL_Crep_Code
    {
        [Key]
        public int CC_Crep_Code_Numero { get; set; }
        public string CC_Crep_Code_Descricao { get; set; }
        public string CC_Crep_Code_Nao_Exige_Valor_Total { get; set; }
        public string CC_Crep_Code_Garantia { get; set; }
        public string CC_Crep_Code_Exige_Valor_Peca { get; set; }
        public string CC_Crep_Code_Exige_Valor_Servico { get; set; }
        public string CC_Crep_Code_Exige_Valor_Total { get; set; }
        public string CC_Crep_Code_Rebil { get; set; }
        public string CC_Crep_Code_Exige_Quantidade { get; set; }
        public string CC_Crep_Code_Conta_Custo { get; set; }
        public string CC_Crep_Code_Conta_Receita { get; set; }
        public string CC_Crep_Code_Mensal { get; set; }
        public string CC_Crep_Code_Tipo_Rebil { get; set; }
        public string CC_Crep_Code_Exige_Imposto { get; set; }
        public string CC_Crep_Code_Conta_Investimento { get; set; }
        public string CC_Crep_Code_Veiculo_Reserva { get; set; }
        public string CC_Crep_Code_Auto_Rebil { get; set; }
        public string CC_Crep_Code_Exige_Km { get; set; }
        public string CC_Crep_Code_Tipo { get; set; }
        public string CC_Crep_Code_Tipo_Pneu { get; set; }
        public string CC_Crep_Code_Fabricante { get; set; }
        public string CC_Crep_Code_Livre { get; set; }
        public string CC_Crep_Code_Grupo_Descricao { get; set; }
        public Nullable<System.DateTime> CC_Crep_Code_Data_Ultima_Atualizacao { get; set; }
        public string CC_Crep_Code_Usuario_Ultima_Atualizacao { get; set; }
        public Nullable<System.DateTime> Data_Ultima_Atualizacao { get; set; }
    }
}
