//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class ALD_ETL_Agreement_Item
    {
        [Key]
        public int AG_Agreement_Numero { get; set; }
        public string AG_Agreement_Crep_Code { get; set; }
        public string AG_Agreement_Rebil_SN { get; set; }
        public Nullable<decimal> AG_Agreement_Item_Valor { get; set; }
        public string AG_Agreement_Item_Descricao { get; set; }
        public Nullable<int> AG_Agreement_Item_Quatidade { get; set; }
        public int AG_Agreement_Linha_Numero { get; set; }
    }
}
