//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Entidades
{
    public partial class ALD_ETL_Database
    {
        [Key]
        public int Num_contrato { get; set; }
        public string Placa { get; set; }
        public string Tipo_contrato { get; set; }
    }
}
