//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALD_ETL_Status
    {
        public int id { get; set; }
        public string tipo { get; set; }
        public System.DateTime dt { get; set; }
        public string st { get; set; }
        public System.DateTime dt_file { get; set; }
    }
}
