//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Controle_NF_Historico
    {
        public int ID { get; set; }
        public Nullable<int> agr_nr { get; set; }
        public string nf_nr { get; set; }
        public Nullable<decimal> vlr_liq { get; set; }
        public Nullable<System.DateTime> dt_rec { get; set; }
        public Nullable<System.DateTime> dt_rec_tri { get; set; }
        public Nullable<System.DateTime> dt_venc { get; set; }
        public Nullable<System.DateTime> dt_env_cp { get; set; }
        public string obs { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> dt_input { get; set; }
        public Nullable<System.DateTime> dt_receb_cp { get; set; }
        public string usuario_receb_cp { get; set; }
        public Nullable<System.DateTime> dt_env_pgto_cp { get; set; }
        public string usuario_env_pgto { get; set; }
        public string deleted { get; set; }
        public string usuario_delete { get; set; }
        public string forn_nome { get; set; }
        public string forn_cnpj { get; set; }
        public Nullable<System.DateTime> dt_delete { get; set; }
        public Nullable<decimal> imp_ret { get; set; }
        public Nullable<decimal> vlr_bruto { get; set; }
        public string agr_type { get; set; }
        public string usuario_receb_fat { get; set; }
        public Nullable<System.DateTime> dt_receb_fat { get; set; }
        public string vcl_num { get; set; }
        public string vcl_placa { get; set; }
        public Nullable<System.DateTime> dt_emiss_nf { get; set; }
        public Nullable<System.DateTime> dt_updt { get; set; }
        public string usuario_updt { get; set; }
        public Nullable<int> ctrv_num { get; set; }
        public string forn_num { get; set; }
        public Nullable<System.DateTime> dt_export_pmi { get; set; }
        public string devolv_forn { get; set; }
        public string usuario_devolv_forn { get; set; }
        public Nullable<System.DateTime> dt_devolv_forn { get; set; }
        public Nullable<System.DateTime> dt_conf_bco_cp { get; set; }
        public string usuario_conf_bco_cp { get; set; }
        public Nullable<decimal> imp_iss { get; set; }
        public Nullable<decimal> imp_pcc { get; set; }
        public Nullable<decimal> imp_inss { get; set; }
        public Nullable<decimal> imp_irrf { get; set; }
        public string invoice_versao { get; set; }
        public string usuario_triagem { get; set; }
        public Nullable<System.DateTime> dt_tri_inc { get; set; }
        public string rebil_sn { get; set; }
        public Nullable<System.DateTime> dt_export_ged { get; set; }
        public Nullable<int> ged_agr { get; set; }
        public Nullable<int> gr_pgto_id { get; set; }
        public string login_temp { get; set; }
        public Nullable<decimal> jur_vlr { get; set; }
        public Nullable<int> acao_tipo { get; set; }
        public Nullable<decimal> vlr_conf_bco { get; set; }
        public string tipo_op_conf_bco { get; set; }
        public string banco_conf_bco { get; set; }
        public string obs_pgto { get; set; }
        public Nullable<System.DateTime> dt_baixa_agr_999 { get; set; }
        public string usuario_baixa_agr_999 { get; set; }
        public string usuario_gr_pgto { get; set; }
        public Nullable<System.DateTime> dt_gr_pgto { get; set; }
        public Nullable<int> agr_nr_temp { get; set; }
        public string mes_fat { get; set; }
        public Nullable<int> fat_rebil_num { get; set; }
        public Nullable<System.DateTime> dt_export_ged_fat { get; set; }
        public string nf_tipo { get; set; }
        public string chave_acesso_sn { get; set; }
        public string chave_acesso { get; set; }
        public string boleto { get; set; }
        public string idvisual_sn { get; set; }
        public string obs_temp { get; set; }
        public string obs_financeiro { get; set; }
        public string obs_manutencao { get; set; }
        public string cod_servico { get; set; }
        public Nullable<System.DateTime> dt_export_nfts { get; set; }
        public Nullable<decimal> imp_iss_perct { get; set; }
        public Nullable<decimal> imp_pcc_perct { get; set; }
        public Nullable<decimal> imp_irrf_perct { get; set; }
        public int id_fila_nf { get; set; }
        public int id_status_importacao { get; set; }
        public bool status_delete_ged { get; set; }
        public Nullable<int> id_status_financeiro { get; set; }
        public System.DateTime dt_transacao { get; set; }
        public int id_tipo_transacao { get; set; }
        public Nullable<int> sp_nr { get; set; }
    
        public virtual Fila_NF Fila_NF { get; set; }
        public virtual Status_Importacao Status_Importacao { get; set; }
        public virtual Tipo_Transacao Tipo_Transacao { get; set; }
    }
}
