//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Solicitacao_Pagamento_Detalhe
    {
        public Solicitacao_Pagamento_Detalhe()
        {
        }

        public Nullable<int> id { get; set; }
        [Required(ErrorMessage = "Por favor informe o Número da Nota Fiscal")]
        public string numero_nf { get; set; }
        public string categoria_nf { get; set; }
        [Required(ErrorMessage = "Por favor informe o Valor")]
        [DataType(DataType.Currency, ErrorMessage = "Valor inválido")]
        public Nullable<decimal> valor { get; set; }
        [Required(ErrorMessage = "Por favor informe a Data de Emissão")]
        [DataType(DataType.Date, ErrorMessage = "Data de Emissão inválida")]
        public Nullable<System.DateTime> dt_emissao { get; set; }
        [Required(ErrorMessage = "Por favor informe a Data de Recebimento")]
        [DataType(DataType.Date, ErrorMessage = "Data de Recebimento inválida")]
        public Nullable<System.DateTime> dt_recebimento { get; set; }
        [Required(ErrorMessage = "Por favor informe a Data de Vencimento")]
        [DataType(DataType.Date, ErrorMessage = "Data de Vencimento inválida")]
        public Nullable<System.DateTime> dt_vencimento { get; set; }
        public Nullable<int> crep_code { get; set; }
        public Nullable<int> qtd { get; set; }
        public Nullable<int> numero_contrato { get; set; }
        public Nullable<int> linha { get; set; }
        [RegularExpression("[0-9]{10}", ErrorMessage = "Número PO inválido")]
        public Nullable<long> numero_po { get; set; }
        [RegularExpression("[Ff]{1}[0-9]{3}", ErrorMessage = "Filial inválida")]
        public string filial { get; set; }
        public Nullable<int> customer_rebill { get; set; }
        public Nullable<int> km { get; set; }
        [StringLength(44, ErrorMessage = "A Chave de Acesso deve conter 44 dígitos")]
        public string chave_acesso { get; set; }
        public string obs { get; set; }
        [RegularExpression("[A-Za-z]{3}[0-9]{4}", ErrorMessage = "Placa inválida")]
        public string placa { get; set; }
        public string placa_subst { get; set; }
        public Nullable<int> id_solicitacao_pagamento { get; set; }
        public Nullable<System.DateTime> dt_criacao { get; set; }
        public Nullable<System.DateTime> dt_atualizacao { get; set; }
        public Nullable<int> prd_id { get; set; }
        public string num_vistoria { get; set; }
        public Nullable<int> id_visual { get; set; }
        public string rebil_sn { get; set; }
        public string mes_fat { get; set; }
        public Nullable<int> fat_rebil_num { get; set; }
        public Nullable<System.DateTime> dt_export_ged_fat { get; set; }
        public decimal  opcionais_veiculo { get; set; }
        public decimal acessorios_veiculo { get; set; }
        public decimal ipva { get; set; }
        public decimal dpvat { get; set; }
        public decimal licenciamento { get; set; }
        public decimal frete { get; set; }
        public decimal despachante { get; set; }
        public decimal outros_servicos { get; set; }
        public Nullable<bool> reused_flag { get; set; }
        [NotMapped]
        [StringLength(1, ErrorMessage = "Reused Flag inválida")]
        [RegularExpression("[SsNn]{1}", ErrorMessage = "Reused Flag inválida")]
        public string reused_flag_sn
        {
            get
            {
                return reused_flag == null? "N" : ((bool)reused_flag ? "S" : "N");
            }
            set
            {
                reused_flag = (value == "S" ? true : false);
            }
        }
        public string dfil { get; set; }
        public string tipo_export { get; set; }
        public decimal nao_rebill_ncva { get; set; }
        public decimal nao_rebill_cva_material { get; set; }
        public decimal nao_rebill_cva_servico { get; set; }

        public virtual Solicitacao_Pagamento Solicitacao_Pagamento { get; set; }
        public virtual Categoria_NF Categoria_NF { get; set; }
    }
}