//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Solicitacao_Pagamento
    {
        public Solicitacao_Pagamento()
        {
            this.Solicitacao_Pagamento_Detalhe = new HashSet<Solicitacao_Pagamento_Detalhe>();
        }

        public Solicitacao_Pagamento Copy()
        {
            return (Solicitacao_Pagamento)this.MemberwiseClone();
        }

        public Nullable<int> id { get; set; }
        [Required(ErrorMessage = "Por favor informe o Fornecedor")]
        public Nullable<int> numero_fornecedor { get; set; }
        [Required(ErrorMessage = "Por favor informe a Diretoria")]
        public Nullable<int> id_diretoria { get; set; }
        [Required(ErrorMessage = "Por favor informe a Forma de Pagamento")]
        public Nullable<int> id_forma_pagamento { get; set; }
        [DataType(DataType.Date, ErrorMessage = "Data de Pagamento inválida")]
        public Nullable<System.DateTime> dt_pagamento { get; set; }
        [Required(ErrorMessage = "Por favor informe o Valor Total")]
        [DataType(DataType.Currency, ErrorMessage = "Valor Total inválido")]
        public Nullable<decimal> valor_total { get; set; }
        public Nullable<int> id_visual { get; set; }
        public string obs { get; set; }
        public int usuario { get; set; }
        public Nullable<int> usuario_atualizacao { get; set; }
        public Nullable<int> gerente { get; set; }
        public Nullable<System.DateTime> dt_aprovacao_gerente { get; set; }
        public Nullable<int> diretor { get; set; }
        public Nullable<System.DateTime> dt_aprovacao_diretor { get; set; }
        public Nullable<int> presidente { get; set; }
        public Nullable<System.DateTime> dt_aprovacao_presidente { get; set; }
        public Nullable<int> aprovador_carpurchase { get; set; }
        public Nullable<System.DateTime> dt_aprovacao_carpurchase { get; set; }
        public Nullable<System.DateTime> dt_criacao { get; set; }
        public Nullable<System.DateTime> dt_atualizacao { get; set; }
        public Nullable<int> id_tipo_solicitacao_pagamento { get; set; }
        public Nullable<int> id_fila_solicitacao_pagamento { get; set; }
        public Nullable<System.DateTime> dt_export_pmi { get; set; }

        public virtual ICollection<Solicitacao_Pagamento_Detalhe> Solicitacao_Pagamento_Detalhe { get; set; }
        public virtual Forma_Pagamento Forma_Pagamento { get; set; }
        public virtual Diretoria Diretoria { get; set; }
        public virtual Tipo_Solicitacao_Pagamento Tipo_Solicitacao_Pagamento { get; set; }
        public virtual Fila_Solicitacao_Pagamento Fila_Solicitacao_Pagamento { get; set; }
        public virtual ALD_ETL_Fornecedores ALD_ETL_Fornecedores { get; set; }
        public virtual ICollection<Documento_Fiscal> Documento_Fiscal { get; set; }
        
        [NotMapped]
        public string arquivo { get; set; }
        [NotMapped]
        public string nomeArquivo { get; set; }
    }
}