export * from './adiantamento.service';
import { AdiantamentoService } from './adiantamento.service';
export * from './aprovacao.service';
import { AprovacaoService } from './aprovacao.service';
export * from './carPurchase.service';
import { CarPurchaseService } from './carPurchase.service';
export * from './crepCode.service';
import { CrepCodeService } from './crepCode.service';
export * from './fornecedor.service';
import { FornecedorService } from './fornecedor.service';
export * from './naoProdutivo.service';
import { NaoProdutivoService } from './naoProdutivo.service';
export * from './produtivo.service';
import { ProdutivoService } from './produtivo.service';
export * from './solicitacaoPagamento.service';
import { SolicitacaoPagamentoService } from './solicitacaoPagamento.service';
export * from './upload.service';
import { UploadService } from './upload.service';
export const APIS = [AdiantamentoService, AprovacaoService, CarPurchaseService, CrepCodeService, FornecedorService, NaoProdutivoService, ProdutivoService, SolicitacaoPagamentoService, UploadService];
